# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invitecode',
            field=models.CharField(blank=True, max_length=40, verbose_name='邀请码'),
        ),
    ]
