# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0002_user_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invitecode',
            field=models.CharField(max_length=40, verbose_name='邀请码'),
        ),
    ]
