# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0002_donate_moneycode_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donate',
            options={'verbose_name_plural': '捐赠'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name_plural': '商品'},
        ),
        migrations.AlterField(
            model_name='moneycode',
            name='user',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='用户名'),
        ),
    ]
