# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0004_auto_20170728_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='moeny',
        ),
        migrations.AddField(
            model_name='shop',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='金额'),
        ),
    ]
