# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0004_invitecode_node'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='menthod',
            new_name='method',
        ),
    ]
