# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0005_auto_20170729_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneycode',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=10, null=True, verbose_name='捐赠金额'),
        ),
    ]
