# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0006_auto_20170722_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='obfs',
            field=models.CharField(choices=[('plain', 'plain'), ('http_simple', 'http_simple'), ('http_post', 'http_post'), ('tls1.2_ticket_auth', 'tls1.2_ticket_auth')], default='plain', max_length=32, verbose_name='混淆'),
        ),
        migrations.AlterField(
            model_name='node',
            name='protocol',
            field=models.CharField(choices=[('auth_sha1_v4', 'auth_sha1_v4'), ('auth_aes128_md5', 'auth_aes128_md5'), ('auth_aes128_sha1', 'auth_aes128_sha1'), ('auth_chain_a', 'auth_chain_a'), ('origin', 'origin')], default='origin', max_length=32, verbose_name='协议'),
        ),
    ]
