# Generated by Django 2.0.1 on 2018-02-10 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='owner',
            field=models.ForeignKey(help_text='用户ID', on_delete=django.db.models.deletion.CASCADE, related_name='code_owner', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
