# Generated by Django 2.0.6 on 2018-06-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=64, verbose_name='用户id')),
                ('image', models.ImageField(upload_to='pics/', verbose_name='图片名字')),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '用户图片',
                'ordering': ('-create_at',),
            },
        ),
    ]
