# Generated by Django 2.0.6 on 2018-06-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_userpic_media_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpic',
            name='media_id',
            field=models.CharField(blank=True, max_length=72, verbose_name='图片id'),
        ),
    ]
