rules = {
    '网站':'https://www.ehcozone.ml',
    'ss':'请进telegram群获得最新消息 https://t.me/Ehcobreakwa11',
    '节点':'请进telegram群获得最新消息 https://t.me/Ehcobreakwa11',
    '指南': 'http://dwz.cn/ehcowechat',
    '爬虫': 'http://dwz.cn/ehcospider',
    '使用教程': '旧站点即将关闭了，新的请进Telegram群了解信息:\nhttps://t.me/Ehcobreakwa11',
    '客户端': 'http://mp.weixin.qq.com/s/iQDiW4PROIjQuxeOPy7K5g',
    '梯子': 'http://mp.weixin.qq.com/s/CtQwgcvztDTYstpMawLGow',
    '路由器': 'http://mp.weixin.qq.com/s/QiOlBCGZmNE7v0Z9Atc5Rg',
    '黑域': "链接:https://pan.baidu.com/s/1gfCEdnt 密码:v2ze",
    '妹纸图': '链接:https://pan.baidu.com/s/1qY2Rbq8 密码:rqv6',
    '老司机':'链接:http://pan.baidu.com/s/1jH5Cuxg  密码:sp8b',   
    '妹子图': '链接:https://pan.baidu.com/s/1qY2Rbq8 密码:rqv6',
    '谜之屋': 'https://www.ehcozone.ml/ 请不要在微信直接打开',
    '迷之屋': 'https://www.ehcozone.ml/ 请不要在微信直接打开',
    '网站': 'https://www.ehcozone.ml/ 请不要在微信直接打开',
    '群链接': 'https://t.me/Ehcobreakwa11',
    'telegram': 'https://t.me/Ehcobreakwa11',
    '充值':'充值请直接去谜之屋的捐赠界面 用支付宝就行啦',
    '豆瓣电影':'链接:https://pan.baidu.com/s/1i47KJh7  密码:yrho',
    '科学上网':'谜之屋需要邀请码才能注册，在公众号回复邀请码自动获取，谜之屋的地址是https://www.ehcozone.ml',
    'fc游戏':'链接:https://pan.baidu.com/s/1mi3REy8  密码:vmh5',
}
