# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170621_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
