# Generated by Django 2.0.1 on 2018-02-10 10:08

import apps.utils.tool
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180210_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneycode',
            name='code',
            field=models.CharField(blank=True, default=apps.utils.tool.get_long_random_string, editable=False, max_length=40, unique=True, verbose_name='充值码'),
        ),
        migrations.AlterField(
            model_name='moneycode',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=10, null=True, verbose_name='捐赠金额'),
        ),
    ]
