# Generated by Django 2.0.1 on 2018-02-12 13:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0003_auto_20180210_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(default='待编辑', max_length=128, verbose_name='商品描述')),
                ('transfer', models.BigIntegerField(default=1073741824, verbose_name='增加的流量(GB)')),
                ('number', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='金额')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='商品等级')),
                ('time', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)], verbose_name='设置等级时间(天)')),
                ('status', models.IntegerField(choices=[(1, '上架'), (0, '下架')], default=1, verbose_name='商品状态')),
            ],
            options={
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='金额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='购买时间')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Goods')),
                ('user', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to=settings.AUTH_USER_MODEL, verbose_name='购买者')),
            ],
            options={
                'verbose_name_plural': '购买记录',
                'ordering': ('-create_time',),
            },
        ),
    ]
