# Generated by Django 2.0.1 on 2018-02-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_goods_purchasehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='money',
            new_name='number',
        ),
    ]
