# Generated by Django 2.0.1 on 2018-02-16 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20180212_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='user',
            field=models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_user', to=settings.AUTH_USER_MODEL, verbose_name='购买者'),
        ),
    ]
