# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('plan', models.CharField(choices=[('free', 'Free')], default='free', max_length=32, verbose_name='套餐')),
                ('server', models.CharField(max_length=128, verbose_name='服务器IP')),
                ('menthod', models.CharField(choices=[('aes-256-cfb', 'aes-256-cfb'), ('rc4-md5', 'rc4-md5'), ('salsa20', 'salsa20'), ('aes-128-ctr', 'aes-128-ctr')], default='aes-256-cfb', max_length=32, verbose_name='加密类型')),
                ('info', models.CharField(blank=True, max_length=1024, null=True, verbose_name='节点说明')),
                ('status', models.CharField(choices=[('ok', '好用'), ('slow', '不好用'), ('fail', '坏了')], default='ok', max_length=32, verbose_name='状态')),
                ('node_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='节点id')),
            ],
            options={
                'verbose_name_plural': '节点',
                'ordering': ['-node_id'],
            },
        ),
    ]
