# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['node_id'], 'verbose_name_plural': '节点'},
        ),
        migrations.RemoveField(
            model_name='node',
            name='plan',
        ),
    ]
