# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import ssserver.tools


class Migration(migrations.Migration):

    dependencies = [
        ('ssserver', '0002_auto_20170714_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('code', models.CharField(blank=True, default=ssserver.tools.get_long_random_string, max_length=40, primary_key=True, serialize=False, verbose_name='邀请码')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
