# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssserver', '0003_invitecode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitecode',
            options={'ordering': ('-time_created',), 'verbose_name_plural': '邀请码'},
        ),
    ]
